### ISSUE TITLE
E2 Motionboard

### ISSUE THREAD

**Issue by Proschi3D** [Raise3D/Reprap-Raise3D-E2-Series#1]
could I get a pinout from the motion controller, please?
A schematic circuit diagram like the one offered by Duet?
Many Thanks

**Comment by Raise3D** [comment]
![4E2ACD57-25B1-4845-8D71-BCAC0441F3FE](https://user-images.githubusercontent.com/16485188/105929269-31a76100-6082-11eb-99b3-5852371d6508.png)
Please refer to the pin-out. Currently, the circuit diagram is not available now. It's now under review. If you have a specific question and purpose, we can provide the information that you need.

**Comment by Proschi3D** [comment]
Hi there,
i have the problem like many my E2 is pausing in print.

Now I have found that if I access the Motionboard directly via a Raspberry Pi with a touch display and Repetier Server, I no longer have a problem with pausing during printing.
So I flashed a newer version of the Duet Wifi firmware.
Now there are problems with the configuration.
Since I have no pin assignment, the Z-Probe, Thermocouple and the right extruder do not work.

It would be nice if you could help me.

**Comment by Raise3D** [comment]
Hi, could you send an Email to tim.wu@raise3d.com, so we could help you with setup commands that could directly initial all the hardware. Also for the random pause issue please contact support, it should be a communication IC issue between touchscreen and motion controller. Our own protocol adds a lot of extra communication for advanced functions. Our support team could definitely help.

**Comment by Proschi3D** [comment]
Thank you for your quick response. I have sent an Email

**Comment by Raise3D** [comment]
More than happy to help. :D This issue will be closed.
